// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"server/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/account/create",
				Handler: CreateAccountHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/supported-permissions",
				Handler: GetSupportedPermissionsHandler(serverCtx),
			},
		},
	)
}
