// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ChainInfo struct {
	ChainId string `json:"chainId"`
	Name    string `json:"name"`
}

type CreateAccountReq struct {
	PublicKeyX   string `json:"publicKeyX"`
	PublicKeyY   string `json:"publicKeyY"`
	CredentialId string `json:"credentialId"`
}

type CreateAccountResp struct {
}

type GetSupportedPermissionsReq struct {
}

type GetSupportedPermissionsResp struct {
	Permissions []PermissionDetail `json:"permissions"`
}

type PermissionDetail struct {
	Type         string      `json:"type"`
	ProposedName string      `json:"proposedName"`
	Chains       []ChainInfo `json:"chains"`
	RuleTypes    []string    `json:"ruleTypes"`
}
