// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type ChainInfo struct {
	ChainId string `json:"chainId"`
	Name    string `json:"name"`
}

type CreateAccountReq struct {
	PublicKeyX   string `json:"publicKeyX"`
	PublicKeyY   string `json:"publicKeyY"`
	CredentialId string `json:"credentialId"`
}

type CreateAccountResp struct {
}

type GetSupportedPermissionsReq struct {
}

type GetSupportedPermissionsResp struct {
	Permissions []PermissionDetail `json:"permissions"`
}

type PermissionDetail struct {
	Type         string      `json:"type"`
	ProposedName string      `json:"proposedName"`
	Chains       []ChainInfo `json:"chains"`
	RuleTypes    []string    `json:"ruleTypes"`
}

type PermissionInfo struct {
	Type string `json:"type"`
	Data string `json:"data"`
}

type Rule struct {
	Type string `json:"type"`
	Data string `json:"data"`
}

type SubmitPermissionReq struct {
	ChainId             string         `json:"chainId"`
	From                string         `json:"from,omitempty"`
	To                  string         `json:"to"`
	IsAdjustmentAllowed bool           `json:"isAdjustmentAllowed"`
	Permission          PermissionInfo `json:"permission"`
	Rules               []Rule         `json:"rules"`
}

type SubmitPermissionResp struct {
}
