// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type CreateAccountReq struct {
	PublicKeyX   string `json:"publicKeyX"`
	PublicKeyY   string `json:"publicKeyY"`
	CredentialId string `json:"credentialId"`
}

type CreateAccountResp struct {
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}
